accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
         template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasque.urls')),
    path('accounts/', include('accounts.urls'))
]

tasque/urls.py
from django.urls import path
from . import views

app_name = 'tasque'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('task/create/', views.TaskCreateView.as_view(), name='task_create'),
    path('task/create/complete/', views.TaskCreateCompleteView.as_view(),
         name='task_create_complete'),
    path('task/do/<int:tag_id>/', views.taskDoView, name='task_do'),
    path('task/delete/<uuid:task_id>',
         views.taskDeleteView, name='task_delete'),
    path('task/done/<uuid:task_id>', views.taskDoneView, name='task_done'),
    path('tag/list/', views.TagListView, name='tag_list'),
    path('tag/create/', views.tagCreateView, name='tag_create'),
    path('tag/delete/<int:tag_id>/', views.tagDeleteView, name='tag_delete'),
    #     path('tag/create/complete/', views.TagCreateCompleteView.as_view(),
    #          name='tag_create_complete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load static %} {% bootstrap_css %}

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Tasque</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>

<body class="bg-light">
  <h1 class="text-center m-5">
    <a href="{% url 'tasque:index' %}" class="text-jade font-title text-uppercase fw-light">
      Tasque
    </a>
  </h1>
  {% if not user.is_anonymous %}
  <h5 class="mt-3 mb-3 text-center text-secondary">
    ようこそ {{user.username}} さん
  </h5>
  <h5 class="mt-3 mb-3 text-center">
    <a href="{% url 'accounts:logout' %}" class="text-secondary font-title">ログアウト</a>
  </h5>
  {% else %}
  <h5 class="mt-3 mb-3 text-center">
    <a href="{% url 'accounts:signup' %}" class="text-secondary font-title">ユーザー登録</a>
  </h5>
  <h5 class="mt-3 mb-3 text-center">
    <a href="{% url 'accounts:login' %}" class="text-secondary font-title">ログイン</a>
  </h5>
  {% endif %}

  <div class="container">
    <div class="border-bottom"></div>
    {% block content %}{% endblock %}
    <div class="border-bottom mt-5"></div>
  </div>

  <h4 class="mt-5 text-center">
    <a href="{% url 'tasque:index' %}" class="text-secondary font-title">TOP</a>
  </h4>
  <h5 class="mt-1 text-center">
    <a href="{% url 'tasque:tag_list' %}" class="text-secondary font-title">タグの設定</a>
  </h5>
  <h5 class="mt-1 text-center">
    <a href="{% url 'tasque:task_create' %}" class="text-secondary font-title">タスク作成</a>
  </h5>
  <h5 class="mt-1 text-center">
    <a href="{% url 'tasque:task_do' tag_id=1  %}" class="text-secondary font-title">タスク実行</a>
  </h5>
</body>

</html>

templates/index.html
{% extends 'base.html' %} {% block content %}

<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タグの設定</h2>
<p class="text-d">タスクを整理するためのタグを追加・削除します</p>
<a href="{% url 'tasque:tag_list' %}">
  <button class="btn btn-outline-jade font-title d-block mx-auto">移動</button>
</a>
<h2 class="leftcolor-green text-b font-title mt-5 mb-3">タスク作成</h2>
<p class="text-d">
  新たにタスクを作成します<br />締切やタグを設定することでタスクの優先度を上げることができます
</p>
<a href="{% url 'tasque:task_create' %}">
  <button class="btn btn-outline-jade font-title d-block mx-auto">移動</button>
</a>

<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タスク実行</h2>
<p class="text-d">タスクを一件ずつこなします</p>
<a href="{% url 'tasque:task_do' tag_id=1 %}" class="text-b font-title">
  <button class="btn btn-outline-jade font-title d-block mx-auto">移動</button>
</a>

{% endblock %}

templates/login.html
{% extends 'base.html' %} {% block content %}
<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">ログイン</h2>
<p class="text-d mb-3">
  ユーザー登録が済んでいない方は<a href="{% url 'accounts:signup' %}"
    >ユーザー登録</a
  >をしてください<br />登録済みの方はログインすることでアプリを使用できます
</p>
<form method="POST">
  {% csrf_token %}
  <input class="form-control" name="username" />
  <br />

  <input class="form-control" type="password" name="password" />
  <br />

  <button
    class="btn btn-outline-jade font-title d-block mx-auto"
    type="submit"
    value="ログイン"
  >
    ログイン
  </button>
</form>

{% endblock %}

templates/signup.html
{% extends 'base.html' %} {% block content %}

<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">ユーザー登録</h2>
<form method="post" novalidate>
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-outline-jade font-title d-block mx-auto">
    登録
  </button>
</form>

{% endblock %}

templates/tag_create_complete.html
{% extends 'base.html' %} {% block content %}
<h1>Tag Create Created</h1>
<a href="{% url 'tasque:tag_create' %}">さらにTagを作る</a>
{% endblock %}

templates/tag_list.html
{% extends 'base.html' %} {% block content %}


  <h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タグ一覧</h2>
  <ul class="list-group">
    {% for tag in tag_list %}
    <li
      class="list-group-item d-flex align-items-center list-unstyled row m-1 p-2"
    >
      <h5 class="text-jade col-8 m-0">{{tag}}</h5>
      {% if not tag.id == 1 %}
      <form method="post" action="{% url 'tasque:tag_delete' tag.id %}"  class="ml-auto">
        {% csrf_token %}
      <button type="submit" class="btn btn-outline-danger font-title">削除</button>
      </form>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
  <h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タグ登録</h2>
  <form method="post" action="{% url 'tasque:tag_create' %}" class="m-1 p-2">
  {% csrf_token %}
  <input class="form-control" type="text" name="tag_name" placeholder="登録するタグを入力"></input>
  <button type="submit" class="btn btn-secondary d-block mt-3 mx-auto font-title">
    追加
  </button>
</form>


{% endblock %}

templates/task_create.html
{% extends 'base.html' %} {% block content %}
<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タスク作成</h2>

<form method="post" class="mt-5">
  {% csrf_token %}
  <div class="container form-group">{{form.as_p}}</div>
  <button
    type="submit"
    class="btn btn-secondary d-block mt-5 mx-auto font-title"
  >
    投稿
  </button>
</form>
{% endblock %}

templates/task_create_complete.html
{% extends 'base.html' %} {% block content %}
<p class="mt-5 mb-3">タスクの作成が完了しました</p>

{% endblock %}

templates/task_do.html
{% extends 'base.html' %} {% block content %}

<h2 class="leftcolor-green mt-5 mb-3 text-b font-title">タグでソートする</h2>
{% for tag in all_tag %}

<li class="list-group-item d-flex align-items-center list-unstyled row m-1 p-2">
  <h5 class="text-jade col-8 m-0">{{tag.name}}</h5>
  <a href="{% url 'tasque:task_do' tag_id=tag.id %}" class="ml-auto">
    {% if tag.id == now_tag.id %}
    <button type="submit" class="btn btn-outline-secondary font-title">
      選択中
    </button>
    {% else %}
    <button type="submit" class="btn btn-outline-jade font-title">選択</button>
    {% endif %}
  </a>
</li>
{% endfor %}

<h2 class="leftcolor-green mt-5 mb-3 text-b font-title" id="next-task">
  次のタスク
</h2>

<div class="card">
  {% if tasks.0.due_date is not None %}
  <h5 class="text-right card-header">期限：{{tasks.0.due_date}}</h5>
  {% endif %}
  <div class="card-body">
    {% if tasks %}
    <h2 class="card-title text-d font-title">{{tasks.0.title}}</h2>
    <p class="card-text">{{tasks.0.detail}}</p>
    <div class="border-bottom"></div>
    <div class="row justify-content-center mt-3">
      <div class="btn-group">
        <form method="post" action="{% url 'tasque:task_delete' tasks.0.id %}">
          {% csrf_token %}
          <button
          class="btn btn-outline-danger mr-1"
          type="submit"
          name="delete"
          >
          削除
        </button>
      </form>
      <form method="post" action="{% url 'tasque:task_done' tasks.0.id %}">
        {% csrf_token %}
          <button class="btn btn-secondary ml-1" type="submit" name="done">
            完了
          </button>
        </form>
      </div>
    </div>
    {% else %}
    <p class="card-text">このタグのTaskはありません</p>
    
    {% endif %}
  </div>
</div>
<h2 class="leftcolor-green mt-5 mb-3 text-b font-title" id="next-task">
  以降のタスク
</h2>
{% for task in tasks %}

{% if not forloop.first %}
<li class="list-group-item d-flex align-items-center list-unstyled row m-1 p-2">
  <h5 class="text-jade col-8 m-0">{{task.title}}</h5>
</li>
{% endif %}
{% endfor %}
{% endblock %}